PLATFORM_INCLUDE_DIRECTORY	:= $(PLATFORM_TOOL_DIRECTORY)/devkit/sh4/target/usr/include

PLATFORM_LIB_DIRECTORY		:= $(PLATFORM_TOOL_DIRECTORY)/devkit/sh4/target/usr/lib

PLATFORM_INCLUDE_DIRECTORYS	:= $(PLATFORM_INCLUDE_DIRECTORY) \
				$(PLATFORM_INCLUDE_DIRECTORY)/c++/4.2.1 \
				$(PLATFORM_INCLUDE_DIRECTORY)/c++/4.2.1/sh4-linux

PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS)

PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS) -L$(PLATFORM_LIB_DIRECTORY)
PLATFORM_LINK_FLAGS		:= $(PLATFORM_LINK_FLAGS)

