PLATFORM_INCLUDE_DIRECTORY      := $(PLATFORM_TOOL_DIRECTORY)/mtk-toolchain/gnuarm-4.4.2/cross-tools/arm11/armv6z-mediatek-linux-gnueabi/include
PLATFORM_INCLUDE_DIRECTORYS     := $(PLATFORM_INCLUDE_DIRECTORY) $(PLATFORM_INCLUDE_DIRECTORY)/c++/4.4.2
